### PR TITLE
Added support for managing release assets

### PR DESCRIPTION
**Pull request by nicholasdille**
Hi @pcgeek86,

I have implemented handling GitHub release assets for a project of mine and thought this might look nice in your module ;-)

I have added the following cmdlets:
- `Get-GitHubReleaseAsset`
- `New-GitHubReleaseAsset`
- `Remove-GitHubReleaseAsset`

To support this, it was necessary to update `Invoke-GitHubApi` to support upload.github.com for API calls.

### CODE REVIEW

**Comment by pcgeek86** [comment]
Thanks for these submissions @nicholasdille. I need to do some work on my side before I put more effort on this project. I'll do some research and hopefully circle back and merge this in.

**Edit**: Just submitted a ticket internally to see if I can get this merged.

**Comment by pcgeek86** [comment]
Do we need to add these new functions to the module manifest?

**Comment by nicholasdille** [comment]
Yes, adding and removing release assets should be exposed to the user. I am very actively using those functions for continuous delivery of my PowerShell modules. I would love to import them from your module :-)

**Comment by pcgeek86** [comment]
@nicholasdille cool, would you be interested in submitting a PR to add them to the manifest as well?

**Comment by nicholasdille** [comment]
This should have taken care of the module manifest

**Comment by pcgeek86** [comment]
Thanks @nicholasdille! Much appreciated.

**Pull request merged**
